package com.im.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.im.entity.ApplyRecordEntity;
import com.im.entity.FriendInforEntity;
import com.im.entity.MobileInforEntity;

import com.im.greendao.ApplyRecordEntityDao;
import com.im.greendao.FriendInforEntityDao;
import com.im.greendao.MobileInforEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig applyRecordEntityDaoConfig;
    private final DaoConfig friendInforEntityDaoConfig;
    private final DaoConfig mobileInforEntityDaoConfig;

    private final ApplyRecordEntityDao applyRecordEntityDao;
    private final FriendInforEntityDao friendInforEntityDao;
    private final MobileInforEntityDao mobileInforEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        applyRecordEntityDaoConfig = daoConfigMap.get(ApplyRecordEntityDao.class).clone();
        applyRecordEntityDaoConfig.initIdentityScope(type);

        friendInforEntityDaoConfig = daoConfigMap.get(FriendInforEntityDao.class).clone();
        friendInforEntityDaoConfig.initIdentityScope(type);

        mobileInforEntityDaoConfig = daoConfigMap.get(MobileInforEntityDao.class).clone();
        mobileInforEntityDaoConfig.initIdentityScope(type);

        applyRecordEntityDao = new ApplyRecordEntityDao(applyRecordEntityDaoConfig, this);
        friendInforEntityDao = new FriendInforEntityDao(friendInforEntityDaoConfig, this);
        mobileInforEntityDao = new MobileInforEntityDao(mobileInforEntityDaoConfig, this);

        registerDao(ApplyRecordEntity.class, applyRecordEntityDao);
        registerDao(FriendInforEntity.class, friendInforEntityDao);
        registerDao(MobileInforEntity.class, mobileInforEntityDao);
    }
    
    public void clear() {
        applyRecordEntityDaoConfig.clearIdentityScope();
        friendInforEntityDaoConfig.clearIdentityScope();
        mobileInforEntityDaoConfig.clearIdentityScope();
    }

    public ApplyRecordEntityDao getApplyRecordEntityDao() {
        return applyRecordEntityDao;
    }

    public FriendInforEntityDao getFriendInforEntityDao() {
        return friendInforEntityDao;
    }

    public MobileInforEntityDao getMobileInforEntityDao() {
        return mobileInforEntityDao;
    }

}
