package com.im.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.im.entity.FriendInforEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FRIEND_INFOR_ENTITY".
*/
public class FriendInforEntityDao extends AbstractDao<FriendInforEntity, Long> {

    public static final String TABLENAME = "FRIEND_INFOR_ENTITY";

    /**
     * Properties of entity FriendInforEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Uuid = new Property(0, String.class, "uuid", false, "UUID");
        public final static Property Username = new Property(1, String.class, "username", false, "USERNAME");
        public final static Property Nickname = new Property(2, String.class, "nickname", false, "NICKNAME");
        public final static Property Mobile = new Property(3, String.class, "mobile", false, "MOBILE");
        public final static Property Portrait = new Property(4, String.class, "portrait", false, "PORTRAIT");
        public final static Property Gender = new Property(5, String.class, "gender", false, "GENDER");
        public final static Property Status = new Property(6, int.class, "status", false, "STATUS");
        public final static Property RealName = new Property(7, String.class, "realName", false, "REAL_NAME");
        public final static Property CommunityName = new Property(8, String.class, "communityName", false, "COMMUNITY_NAME");
        public final static Property SortLetters = new Property(9, String.class, "sortLetters", false, "SORT_LETTERS");
        public final static Property Id = new Property(10, Long.class, "id", true, "_id");
    }


    public FriendInforEntityDao(DaoConfig config) {
        super(config);
    }
    
    public FriendInforEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FRIEND_INFOR_ENTITY\" (" + //
                "\"UUID\" TEXT," + // 0: uuid
                "\"USERNAME\" TEXT," + // 1: username
                "\"NICKNAME\" TEXT," + // 2: nickname
                "\"MOBILE\" TEXT," + // 3: mobile
                "\"PORTRAIT\" TEXT," + // 4: portrait
                "\"GENDER\" TEXT," + // 5: gender
                "\"STATUS\" INTEGER NOT NULL ," + // 6: status
                "\"REAL_NAME\" TEXT," + // 7: realName
                "\"COMMUNITY_NAME\" TEXT," + // 8: communityName
                "\"SORT_LETTERS\" TEXT," + // 9: sortLetters
                "\"_id\" INTEGER PRIMARY KEY );"); // 10: id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FRIEND_INFOR_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FriendInforEntity entity) {
        stmt.clearBindings();
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(1, uuid);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(2, username);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(3, nickname);
        }
 
        String mobile = entity.getMobile();
        if (mobile != null) {
            stmt.bindString(4, mobile);
        }
 
        String portrait = entity.getPortrait();
        if (portrait != null) {
            stmt.bindString(5, portrait);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(6, gender);
        }
        stmt.bindLong(7, entity.getStatus());
 
        String realName = entity.getRealName();
        if (realName != null) {
            stmt.bindString(8, realName);
        }
 
        String communityName = entity.getCommunityName();
        if (communityName != null) {
            stmt.bindString(9, communityName);
        }
 
        String sortLetters = entity.getSortLetters();
        if (sortLetters != null) {
            stmt.bindString(10, sortLetters);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(11, id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FriendInforEntity entity) {
        stmt.clearBindings();
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(1, uuid);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(2, username);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(3, nickname);
        }
 
        String mobile = entity.getMobile();
        if (mobile != null) {
            stmt.bindString(4, mobile);
        }
 
        String portrait = entity.getPortrait();
        if (portrait != null) {
            stmt.bindString(5, portrait);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(6, gender);
        }
        stmt.bindLong(7, entity.getStatus());
 
        String realName = entity.getRealName();
        if (realName != null) {
            stmt.bindString(8, realName);
        }
 
        String communityName = entity.getCommunityName();
        if (communityName != null) {
            stmt.bindString(9, communityName);
        }
 
        String sortLetters = entity.getSortLetters();
        if (sortLetters != null) {
            stmt.bindString(10, sortLetters);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(11, id);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10);
    }    

    @Override
    public FriendInforEntity readEntity(Cursor cursor, int offset) {
        FriendInforEntity entity = new FriendInforEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // uuid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // username
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // nickname
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mobile
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // portrait
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // gender
            cursor.getInt(offset + 6), // status
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // realName
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // communityName
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // sortLetters
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10) // id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FriendInforEntity entity, int offset) {
        entity.setUuid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUsername(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNickname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMobile(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPortrait(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGender(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStatus(cursor.getInt(offset + 6));
        entity.setRealName(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCommunityName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSortLetters(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setId(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FriendInforEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FriendInforEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FriendInforEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
