package com.youmai.hxsdk.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.youmai.hxsdk.db.bean.ContactBean;
import com.youmai.hxsdk.db.bean.GroupInfoBean;
import com.youmai.hxsdk.db.bean.CacheMsgBean;

import com.youmai.hxsdk.db.dao.ContactBeanDao;
import com.youmai.hxsdk.db.dao.GroupInfoBeanDao;
import com.youmai.hxsdk.db.dao.CacheMsgBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactBeanDaoConfig;
    private final DaoConfig groupInfoBeanDaoConfig;
    private final DaoConfig cacheMsgBeanDaoConfig;

    private final ContactBeanDao contactBeanDao;
    private final GroupInfoBeanDao groupInfoBeanDao;
    private final CacheMsgBeanDao cacheMsgBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactBeanDaoConfig = daoConfigMap.get(ContactBeanDao.class).clone();
        contactBeanDaoConfig.initIdentityScope(type);

        groupInfoBeanDaoConfig = daoConfigMap.get(GroupInfoBeanDao.class).clone();
        groupInfoBeanDaoConfig.initIdentityScope(type);

        cacheMsgBeanDaoConfig = daoConfigMap.get(CacheMsgBeanDao.class).clone();
        cacheMsgBeanDaoConfig.initIdentityScope(type);

        contactBeanDao = new ContactBeanDao(contactBeanDaoConfig, this);
        groupInfoBeanDao = new GroupInfoBeanDao(groupInfoBeanDaoConfig, this);
        cacheMsgBeanDao = new CacheMsgBeanDao(cacheMsgBeanDaoConfig, this);

        registerDao(ContactBean.class, contactBeanDao);
        registerDao(GroupInfoBean.class, groupInfoBeanDao);
        registerDao(CacheMsgBean.class, cacheMsgBeanDao);
    }
    
    public void clear() {
        contactBeanDaoConfig.clearIdentityScope();
        groupInfoBeanDaoConfig.clearIdentityScope();
        cacheMsgBeanDaoConfig.clearIdentityScope();
    }

    public ContactBeanDao getContactBeanDao() {
        return contactBeanDao;
    }

    public GroupInfoBeanDao getGroupInfoBeanDao() {
        return groupInfoBeanDao;
    }

    public CacheMsgBeanDao getCacheMsgBeanDao() {
        return cacheMsgBeanDao;
    }

}
